Repository pepero-1/liar-game, pull requests merged in 2023-11, with the labels that each got.

#5 useFireFetch, useFetch, index.css 수정
  src/hooks/useFetch.ts
  src/hooks/useFireFetch.ts
  src/index.css
  src/pages/Example/index.tsx
  src/pages/Login/index.tsx
Labels: bug, feat

#6 커스텀 훅 타입 및 환경변수 추가, 예시 페이지 소켓통신 추가
  src/hooks/useFetch.ts
  src/hooks/useFireFetch.ts
  src/pages/Example/index.tsx
Labels: bug, feat

#8 useFetch 에러 리턴 추가, 예시 페이지 서버채팅 추가
  src/hooks/useFetch.ts
  src/pages/Example/index.tsx
  vite.config.ts
Labels: bug, feat

#10 유저초대, 초대 알림 기능
  src/components/Main/CreateGameModal/index.tsx
  src/components/common/UserCard/index.tsx
  src/pages/Example/index.tsx
  src/pages/Login/index.tsx
Labels: feat

#11 게임 생성 시 게임 페이지로 이동
  src/App.tsx
  src/components/Main/CreateGameModal/index.tsx
  src/hooks/useFireFetch.ts
Labels: feat

#13 게임 입장 시 콘솔에 데이터 출력
  src/components/Main/CreateGameModal/index.tsx
  src/components/common/UserCard/index.tsx
  src/pages/Game/index.tsx
Labels: feat

#14 토스트 팝업 ui 데이터 연결, 초대 거절 수락 기능 추가
  src/components/Main/CreateGameModal/index.tsx
  src/components/common/ToastNotice/index.tsx
  src/pages/Example/index.tsx
Labels: feat

#24 게임방 목록 페이지 UI 구현
  src/App.tsx
  src/assets/logo1.png
  src/components/Main/GameLists/index.tsx
Labels: feat

#25 Feature/#3 랜덤 키워드, 라이어 지정
  src/App.tsx
  src/components/Game/Keyword/index.tsx
  src/data/category.json
  src/pages/Game/index.tsx
Labels: feat, style

#26 게임 생성 시 이모티콘 추가 기능, 로딩 ui 추가
  package-lock.json
  package.json
  src/components/Main/CreateGameModal/index.tsx
  src/components/common/Loader/index.tsx
  src/pages/Example/index.tsx
Labels: bug, feat

#27 Feature/#9 회원 가입 기능
  package-lock.json
  package.json
  src/components/Login/SignUpModal/index.tsx
Labels: feat

#28 초대 팝업 소켓 통신 코드 수정, 메시지 중복 문제 해결, 소켓 연결 모듈화(useSocket 제거)
  src/components/Main/CreateGameModal/index.tsx
  src/hooks/useSocket.ts
  src/pages/Example/index.tsx
  src/socket/socket.ts
Labels: bug, feat

#29 Feature/#7 게임 목록 페이지 유저정보 , 전체유저정보 구현
  src/components/Main/GameLists/index.tsx
Labels: feat

#30 [FIX] 초대 인원 제한, 게임 초대 수락 시 게임 입장
  src/components/Main/CreateGameModal/index.tsx
  src/components/common/ToastNotice/index.tsx
  src/components/common/UserCard/index.tsx
  src/hooks/useFetch.ts
  src/pages/Example/index.tsx
Labels: bug

#31 Feature/#9 로그인, 로그인페이지UI, 회원가입 모달
  index.html
  src/components/Login/LoginForm/index.tsx
  src/components/Login/SignUpModal/index.tsx
  src/hooks/useAuth.ts
  src/main.tsx
  src/pages/Login/index.tsx
  src/pages/Main/user/index.tsx
  src/recoil/atoms/authState.ts
  src/recoil/atoms/userState.ts
Labels: feat, style

#35 Feature/#9 로그인시 아이디 저장
  src/components/Game/GameChat/index.tsx
  src/components/Login/LoginForm/index.tsx
  src/hooks/useAuth.ts
  src/pages/Login/index.tsx
  src/pages/Main/user/index.tsx
  src/recoil/atoms/userState.ts
Labels: feat

#36 초대 팝업 오류 수정, 유저 정보 리코일로 가져오기
  src/components/Main/CreateGameModal/index.tsx
  src/hooks/useFetch.ts
  src/pages/Example/index.tsx
Labels: bug, feat

#38 게임 입장 시 파이어베이스 업데이트
  src/components/Main/CreateGameModal/index.tsx
  src/components/common/ToastNotice/index.tsx
  src/pages/Example/index.tsx
Labels: feat

#39 Feature/#32 프로필 수정
  src/components/Login/SignUpModal/index.tsx
  src/components/Main/UserConfigModal/index.tsx
  src/pages/Main/user/index.tsx
Labels: feat

#42 Feature/#7 게임방 리스트 불러오기 , 게임방 데이터 적용하기
  src/components/Main/GameCard/index.tsx
  src/components/Main/GameLists/index.tsx
Labels: feat

#45 Feat/#3: 게임 시작 소켓 연결
  src/components/Game/GameChat/index.tsx
  src/components/Game/GameStart/index.tsx
  src/components/Main/CreateGameModal/index.tsx
  src/pages/Example/index.tsx
  src/pages/Game/index.tsx
Labels: feat

#50 Feature/#3 게임 시작 구현
  src/components/Game/GameChat/index.tsx
  src/components/Game/GameStart/index.tsx
  src/components/Game/Keyword/index.tsx
  src/components/Main/CreateGameModal/index.tsx
  src/pages/Game/index.tsx
Labels: feat

#55 Feature/#7 게임방 리스트 페이지 에 게임방 만들기 기능 연결 , 게임방리스트 채팅 분리
  src/components/Main/GameLists/index.tsx
  src/components/Main/GameListsChat/index.tsx
Labels: feat

#59 Feature/#7 채팅 기능 구현
  src/components/Main/GameCard/index.tsx
  src/components/Main/GameLists/index.tsx
  src/components/Main/GameListsChat/index.tsx
Labels: feat

#60 Feature/#51 게임 페이지 UI 수정
  src/components/Game/GameStart/index.tsx
  src/components/Game/Timer/index.tsx
  src/pages/Game/index.tsx
Labels: feat

#63 Feat/#51: 게임 종료 시 current 상태 수정
  src/components/Game/GameStart/GameStartModal.tsx
  src/components/Game/GameStart/index.tsx
  src/pages/Game/index.tsx
Labels: bug

#67 사용자 입 퇴장 상태 수정, 안 쓰는 파일 제거, 타이머 40초로 증가
  src/components/Game/GameChat/index.tsx
  src/components/Game/GameStart/GameStartModal.tsx
  src/components/Game/Keyword/index.tsx
  src/components/Game/Timer/index.tsx
  src/components/Game/User/index.tsx
  src/components/Game/UserOrder/index.tsx
  src/components/Main/CreateNoticeModal/index.tsx
  src/components/Main/GameCard/index.tsx
  src/components/Main/NoticeModal/index.tsx
  src/components/Main/ServerChat/index.tsx
  src/components/Main/UserInfo/index.tsx
  src/components/Main/UserLists/index.tsx
  src/components/Main/UserListsAdmin/index.tsx
  src/components/common/ToastNotice/index.tsx
  src/pages/Game/index.tsx
  src/pages/Main/admin/index.tsx
Labels: bug, feat

#69 Feature/#51 리드미 작성
  README.md
Labels: docs

#72 게임 유저 수 제한 변경, 메인 페이지 게임 입장 제한 변경
  src/components/Main/CreateGameModal/index.tsx
  src/components/Main/GameCard/index.tsx
  src/pages/Main/user/index.tsx
Labels: feat

#76 Feature/#51 리드미 업데이트
  README.md
Labels: docs

#41 Deploys
  .husky/pre-commit
  README.md
  index.html
  package-lock.json
  package.json
  public/_redirects
  src/App.tsx
  src/assets/logo1.png
  src/components/Game/GameChat/index.tsx
  src/components/Game/GameStart/index.tsx
  src/components/Game/Keyword/index.tsx
  src/components/Game/Timer/index.tsx
  src/components/Game/User/index.tsx
  src/components/Game/UserOrder/index.tsx
  src/components/Game/Vote/CalculateVote.tsx
  src/components/Game/Vote/index.tsx
  src/components/Login/LoginForm/index.tsx
  src/components/Login/SignUpModal/index.tsx
  src/components/Main/CreateGameModal/index.tsx
  src/components/Main/CreateNoticeModal/index.tsx
  src/components/Main/GameCard/index.tsx
  src/components/Main/GameLists/index.tsx
  src/components/Main/NoticeModal/index.tsx
  src/components/Main/ServerChat/index.tsx
  src/components/Main/UserConfigModal/index.tsx
  src/components/Main/UserInfo/index.tsx
  src/components/Main/UserLists/index.tsx
  src/components/Main/UserListsAdmin/index.tsx
  src/components/common/ChatBubble.tsx
  src/components/common/Loader/index.tsx
  src/components/common/MyChatBubble.tsx
  src/components/common/SystemChat.tsx
  src/components/common/ToastNotice/index.tsx
  src/components/common/UserCard/index.tsx
  src/data/category.json
  src/hooks/useAuth.ts
  src/hooks/useFetch.ts
  src/hooks/useFireFetch.ts
  src/hooks/useInput.ts
  src/hooks/useSocket.ts
  src/index.css
  src/main.tsx
  src/pages/Example/index.tsx
  src/pages/Game/index.tsx
  src/pages/Login/index.tsx
  src/pages/Main/admin/index.tsx
  src/pages/Main/user/index.tsx
  src/pages/NotFound/index.tsx
  src/recoil/atoms/authState.ts
  src/recoil/atoms/userState.ts
  src/socket/socket.ts
  vite.config.ts
Labels: Deploys
